### ISSUE TITLE
Add to F-Droid repository

### ISSUE THREAD

**Issue by betsythefc** [subassistant/simple-calorie-counter#1]
I have been using your app but am planning to remove the Play Store after rooting my device and rely on the F-Droid app store. Would you upload your app to the F-Droid repository?

http://f-droid.org/wiki/page/Inclusion_Policy
http://f-droid.org/forums/forum/submission-queue/

**Comment by Rudloff** [comment]
There is now a ticket for this here: https://gitlab.com/fdroid/rfp/issues/568

**Comment by doubleblacksoftware** [comment]
Released 1.0
